### ISSUE TITLE
Where should I put my eslint config (eslintrc.*)?

### ISSUE THREAD

**Issue by ItzMiracleOwO** [reviewdog/action-eslint#118]
Where should I put my eslintrc.* if I use it? Is it `.github/workflows/reviewdog.yml` or just in root dir 🤔

**Comment by markrity** [comment]
@ItzMiracleOwO If you put your `eslintrc` file at root of project , you don't need to specify anything
you have the argument `eslint_flags: '.'` at `'.'` by default. If you put it anywhere else like `/src` you should specify `eslint_flags: '/src'` 


Good luck.
