### ISSUE TITLE
Cannot running eslint with v1.18.0

### ISSUE THREAD

**Issue by kdevkr** [reviewdog/action-eslint#162]
#### Actions Env
Version: v1.18.0
ESLint Version: 6.14.16
Node Version: actions/setup-node@v2 with 12
Reviewdog Version: v0.14.1

#### Screenshot
![image](https://user-images.githubusercontent.com/17937604/220803302-65cd20b1-fbf2-4c78-8c05-fbc95e06dc15.png)

![image](https://user-images.githubusercontent.com/17937604/220802999-aadc6ec2-72a9-4007-80be-8007952ffe08.png)

**Comment by kdevkr** [comment]
![image](https://user-images.githubusercontent.com/17937604/220805486-5d5dd600-e850-4a62-9909-f53cdcb5ed7a.png)

Why use with tag v0.14.1 ???...

**Comment by yshrsmz** [comment]
This could be a difference between npx version.
npx is completely re-written in v7, so behavior can be different.

I'm not sure which npx version is bundled in Node12, but as Node12 is considered legacy, I suggest you migrate to Node16 or later.
