### ISSUE TITLE
Question about installation

### ISSUE THREAD

**Issue by adityaraute** [reviewdog/action-eslint#166]
Hi

I checked the docs for this action. It was mentioned there that I need to run npm install command.

The thing is, my repo does not use node or any javascript framework. I am only using HTML, CSS, and Vanilla JS for my repo. 

What would be the way to run the linter on my repo in that case? Is it even possible?

**Comment by yshrsmz** [comment]
Calling `npm install -g eslint` in GitHub Action workflow might help, though I strongly recommend adding `package.json` and declaring eslint dependency.

**Comment by adityaraute** [comment]
Even if I'm not using npm for any other JS framework like Node or React?

**Comment by yshrsmz** [comment]
You can choose whatever you want.

But reviewdog does assume that the project has a package.json and eslint is listed in its dependencies or devDependencies.
