### ISSUE TITLE
Action runs unversioned script

### ISSUE THREAD

**Issue by luk-lo** [reviewdog/action-eslint#183]
Hi, I was planning to use this action on our company's GitHub instance but the installation of reviewdog in this action is a bit problematic
https://github.com/reviewdog/action-eslint/blob/10ca150f51dbbb963467c37a03c873ba1fa75f91/script.sh#L11
The `install.sh` script is downloaded from `master`, i.e. the contents could change anytime even if I pin the version of `action-eslint`.
Could the download be pinned to a specific version so it would not change unless the `action-eslint` version changes?

**Comment by javierjulio** [comment]
My understanding is this is by design that the install script is not versioned. Like with other tools this is a way to start the install process with a single, simple command while supporting the case where it can install a specific version of reviewdog. Thank you.

**Comment by luk-lo** [comment]
Maybe this could be revisited in light of recent events (https://www.stepsecurity.io/blog/reviewdog-github-actions-are-compromised) to provide an "immutable" version of this action? See a similar commit at https://github.com/reviewdog/action-setup/commit/e04ffabe3898a0af8d0fb1af00c188831c4b5893
