### ISSUE TITLE
eslint flat config

### ISSUE THREAD

**Issue by stephenjason89** [reviewdog/action-eslint#193]
i just switched to the new flat config and my ci fails now.
<img width="1275" alt="image" src="https://github.com/reviewdog/action-eslint/assets/3810177/b78353ee-a739-435d-b5ec-b1cf558baee9">

Is eslint flat config supported?

**Comment by javierjulio** [comment]
@stephenjason89 yes it is. I use it currently on [ActiveAdmin](https://github.com/activeadmin/activeadmin). There really isn’t enough info to go off of here though. Let us know if you have anything new to share. Thank you.

**Comment by javierjulio** [comment]
@stephenjason89 in the second screenshot, the reported error indicates too many warnings are found to be posted. GitHub has hard limits so it's best to keep your PRs as small as possible.
> Error: reviewdog: Too many results (annotations) in diff.

Sorry, I don't know what could be wrong. My suggestion would be to start simple. You can run eslint locally, even with the new config format, and see what it reports. From there try to debug and make small changes. Thanks!
