### ISSUE TITLE
Not working with VueJS

### ISSUE THREAD

**Issue by ChadTaljaardt** [reviewdog/action-eslint#34]
Hello, 

I think I'm having an issue where eslint is not picking up issues in .vue files with the templating engine. 

Do you know if there is a way to get this to work with vue files?

**Comment by haya14busa** [comment]
I guess you need to change`eslint_flags` to support vue files.

**Comment by ChadTaljaardt** [comment]
Thanks, that worked!

**Comment by dominikager** [comment]
@haya14busa @ChadTaljaardt do you have some examples? Thanks a lot!
