### ISSUE TITLE
Github action failing - repo owner issue 

### ISSUE THREAD

**Issue by shamprasadrh** [reviewdog/action-eslint#38]
I am getting issue in github actions as `reviewdog: cannot get repo owner from environment variable. Set CI_REPO_OWNER?`

this issue started occurring recently is anything changed ? 

name: reviewdog
on: [pull_request]
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: eslint
        uses: reviewdog/action-eslint@v1
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GITHUBTOKEN }}
        with:
          github_token: ${{ secrets.GITHUBTOKEN }}
          CI_REPO_OWNER: ${{ secrets.GITHUBTOKEN }}
          reporter: github-pr-review
          eslint_flags: 'src/'

**Comment by haya14busa** [comment]
fixed by https://github.com/reviewdog/action-eslint/pull/40
