### ISSUE TITLE
Can not use eslint when project has peerDependencies conflicts?

### ISSUE THREAD

**Issue by megos** [reviewdog/action-eslint#49]
Use v1.10.0 action-eslint, npm install failed because my project has peer dependencies conflicts and use npm v7.
I want to ignore peerDependencies conflicts when run eslint. What do you think?

https://blog.npmjs.org/post/626173315965468672/npm-v7-series-beta-release-and-semver-major

My project action log below.

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by haya14busa** [comment]
I guess if action-eslint migrate to composite run action https://github.com/reviewdog/reviewdog/issues/732, the problem should be resolved because users can use the same npm.

**Comment by megos** [comment]
Thanks. That’s right.
However, I want to use action even if until that migrate finished.
I'll try to use npm option.

**Comment by megos** [comment]
Thanks for reviewing!
