### ISSUE TITLE
Parsing error not annotated?

### ISSUE THREAD

**Issue by Zodiase** [reviewdog/action-eslint#66]
See the parsing error here: https://github.com/Zodiase/test-github-actions/pull/7/checks?check_run_id=1567104211

![image](https://user-images.githubusercontent.com/1815174/102418469-a92d9f00-3fb2-11eb-9b96-839adf3344e6.png)

But it's not annotated in the PR: 
![image](https://user-images.githubusercontent.com/1815174/102418497-b5b1f780-3fb2-11eb-9ae5-b538a6a95111.png)

**Comment by haya14busa** [comment]
Isn't it just a report of eslint what it cannot parse the script?
Close as expected.
