### ISSUE TITLE
invalid request 

### ISSUE THREAD

**Issue by heyharii** [reviewdog/action-eslint#7]
neeed help, i got this invalid reqeust

v6.7.0
reviewdog: post failed for eslint: failed to post result: POST https://api.github.com/repos/Happy-5/Performance-WebApp/check-runs: 422 Invalid request.

**Comment by TheRealWaldo** [comment]
I'm seeing the same thing.

**Comment by dricazenck** [comment]
Same to me, and later show this message that I am not sure is related: 

`Only 65535 characters are allowed; 66487 were supplied. []`

**Comment by javierjulio** [comment]
This issue has been resolved by https://github.com/reviewdog/reviewdog/pull/1264 so closing. Thank you. Note that GitHub has hard limits. Best advice is to keep your PRs small.
