### ISSUE TITLE
All the workflow runs for a particular PR has PR name instead of commit description

### ISSUE THREAD

**Issue by Sarjasoft** [reviewdog/action-eslint#79]
I am using the action mentioned in the marketplace (https://github.com/marketplace/actions/run-eslint-with-reviewdog)
Wit every new commit push on the Pull-request the name used for each workflow run is that of the PR and not of the particular commit.
How could the workflow run name be changed to that of the particular commit.

In below example the name is always "Update from YT_chem_4"

![image](https://user-images.githubusercontent.com/77265374/114276007-6c465600-9a42-11eb-8502-d7018b65a79d.png)

**Comment by haya14busa** [comment]
It's name from your workflow config, not from this action-eslint.
